# Default values for jla-vote.
namespace: default
servciceweb:
    annotations: {}
registry:
  server: 
  clientId:
  clientSecret:
ratingweb:
  name: heroes-web
  replicaCount: 1
  image:
    repository: itnext/rating-web
    tag: v1
    pullPolicy: Always
  ports:
    external: 8080
    internal: 8080
  restartPolicy: Always
  resources:
    cpu: "0.5"
    memory: "1Gi"
ratingapi:
  name: heroes-api
  replicaCount: 1
  image:
    repository: itnext/rating-api
    tag: v1
    pullPolicy: Always
  ports:
    external: 3000
    internal: 3000
  restartPolicy: Always
  resources:
    cpu: "20m"
    memory: "55M"
cosmosdb:
  database:
    uri: 