apiVersion: apps/v1
kind: Deployment
metadata:
  name:  "{{ .Values.ratingweb.name }}-deploy"
  labels:
    name:  {{ .Values.ratingweb.name }}
spec:
  selector:
    matchLabels:
      name:  {{ .Values.ratingweb.name }}
  replicas: {{ .Values.ratingweb.replicaCount }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name:  {{ .Values.ratingweb.name }}
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image: "{{ .Values.registry.server }}/{{ .Values.ratingweb.image.repository }}:{{ .Values.ratingweb.image.tag }}"
        name:  "{{ .Values.ratingweb.name }}-cntnr"
        resources:
          requests:
            cpu: {{ .Values.ratingweb.resources.cpu }}
            memory: {{ .Values.ratingweb.resources.memory }}
        env:
        - name:  API
          value:  "http://api:{{ .Values.ratingapi.ports.internal }}/"
        - name: KUBE_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: KUBE_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBE_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort:  {{ .Values.ratingapi.ports.internal }}
          name:  {{ .Values.ratingweb.name }}
        imagePullPolicy: {{ .Values.ratingweb.image.pullPolicy }}
        restartPolicy: {{ .Values.ratingweb.restartPolicy }}