apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    name: api
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: {{ .Values.ratingapi.ports.external }}
    targetPort: {{ .Values.ratingapi.ports.internal }}
  selector:
    name: {{ .Values.ratingapi.name }}
